### ISSUE TITLE
Delete some apps from this repo

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/apps#13] opened 2016-10-15 10:43 UTC
This is a follow up discussion of #7 😉 I think we should remove some of the apps inside of this repo. We could also decide to move them out of this repo into their own 🤔 

Apps we should consider about to delete them:

-apptemplate (is not updated an cannot be used as a template for that reason. I think we should remove it. I would link the developers to the developer documentation)

-django_auth (is totally out of date)
- emoji (same reason)
- files_archive (something we want to do here: https://github.com/nextcloud/server/issues/1573)
- files_odfviewer (is not longer developed; follow up seems to be collabora)
- files_sgfviewer (is totally out of date)
- files_svgedit (same reason)
- ownpad_lite (...)
- pong (...)
- pushnotifications (This is now called Activity and Notifications by @nickvergessen)
- reader (...)
- search (...)
- tattoo (...)
- user_oauth (...)
- user_openid_provider (...)
- user_persona (...)
- user_saml (has now its own repo with an working implementation)
- user_vd
- user_webfinger

Apps, we need to check the status:
- files_videoviewer (seems to be not longer used in Nextcloud 10; according to dependencies of this app)
- fluxx_compensator (you have to decide 😁)
- impress (what is the state here @karlitschek)

To conclude: There are only some apps where it would makes sense to keep them. I'd vote for moving them out of this repo, and remove the whole repo instead of keeping this repo up for 2-3 apps ... 😁 

What do you think? @karlitschek @MorrisJobke @nickvergessen

**Comment by nickvergessen** [comment] 2016-10-16 09:50
> To conclude: There are only some apps where it would makes sense to keep them. I'd vote for moving them out of this repo, and remove the whole repo instead of keeping this repo up for 2-3 apps ... 😁

Agreed

**Comment by karlitschek** [comment] 2016-10-16 10:43
pushnotifications is something different then activity :-)
I think there is still the chance that someone picks some of this apps up and improved them. We don't pay for storage here so there is no need to delete this code.
If someone wants to work on something then we can of course move it to it's one repo.

**Comment by jancborchardt** [comment] 2019-05-17 23:47
Closing because the issue is obsolete, we don’t really need to delete any of these apps as Frank said. If someone picks them up, they can do it – but should move them to a dedicated repo instead of this archive/dump. :)

**Closed by jancborchardt** 2019-05-17 23:47 UTC
Labels: enhancement
